// Author  :   Vicen-te
// Date    :   09/09/2023

/*
    Problem Description:
        You are given two strings s and t.

        String t is generated by random shuffling string s and then add one more letter at a random position.
        
        Return the letter that was added to t.


        Ex1:
            Input: s = "abcd", t = "abcde"
            Output: "e"
            Explanation: 'e' is the letter that was added.
        Ex2:
            Input: s = "", t = "y"
            Output: "y"

    Algorithm: 
        For each character in both strings 's' and 't,' perform an XOR operation, obtaining the character that has been added to 't'.

        Time Complexity: O(N) - size of the string (s+t)
        Space Complexity: O(1) - we only use a single char 
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        char difference = 0;
        for (char character : s+t)
        {
            difference ^= character;
        }
        return difference;
    }
};